### ISSUE TITLE
I made you a docker container

### ISSUE THREAD

**Issue by blacktop** [MITRECND/chopshop#53]
I think my repo also works as install documentation for chopshop :wink: Great job on the tool guys it is starting to get as ubiquitous as yara in the InfoSec world.  

Give me the Yara Sigs and ChopShop decoders, it's all I hear!!

https://github.com/blacktop/docker-chopshop

**Comment by wxsBSD** [comment]
So I don't know anything about Docker but this is certainly welcome, so thank you for doing it! Is this something we can do in our repository and have new versions automatically pushed somewhere? Rather than have you maintain this can we automate it and do it in our repo?

**Comment by Mraoul** [comment]
I took a look at the dockerfile -- the process basically grabs everything from git on the fly, so as long as the install scripts aren't broken and dependencies don't change, building based on the dockerfile should always work. Since, I believe, trusted builds only trigger a re-build on a git commit, the repo/image on the registry might be out of date if something is changed upstream.

Btw, this is awesome

**Comment by blacktop** [comment]
@wxsBSD @Mraoul thanks guys!!!

Like @Mraoul said I am just git pulling from all your repos.  So we could do two things:
 - You could go into the Settings for this repo and click **Webhooks and Services** -> **Add a Webhook.**  In the Payload URL you would put `https://registry.hub.docker.com/u/blacktop/chopshop/trigger/<TriggerToken>` then when ever you push to your repo it would cause an updated Docker container to be automatically built in the [Docker Registry](registry.hub.docker.com) keeping it in sync with your code.
 - I could create a pull request and add it to your repo making me an honorary MITRE employee :sunglasses:, it would work the same way except it would live in your repo and you would need to create an account on the [Docker Registry](registry.hub.docker.com)

@wxsBSD to give you a little background on [Docker](https://www.docker.com). 

'Docker is doing to apt, what apt did to tar files' - Bryan Cantrill, CTO of [Joyent](https://www.joyent.com) (the Node.JS guys) also one of the developers of [DTrace](https://en.wikipedia.org/wiki/DTrace).

It is a way of packaging software with all of it's dependancies in a very exciting way.

**Comment by wxsBSD** [comment]
I'm familiar with the concepts of docker, but I have no clue how to actually create them so thank you for the quick run down. My personal opinion is you send a PR to get this all setup in our repo and either @mraoul or myself will create the docker registry account when we accept it.

**Comment by packet-rat** [comment]
Wes, et al,

Check out Kitematic: https://kitematic.com.  Provides a very nice GUI based Docker framework.  It's a very active community, tools, etc.  You can be up and running in 5-10 minutes.

I've used it extensively on Mac OSX and highly recommend it for developers, lab infrastructure, tool and frameworks evaluation, etc  runs the Docker stub on VirtualBox.  Haven't tested the new efforts for Windows support.

Patrick Maroney


On Jul 3, 2015, at 10:33 PM, Wesley Shields <notifications@github.com> wrote:

I'm familiar with the concepts of docker, but I have no clue how to actually create them so thank you for the quick run down. My personal opinion is you send a PR to get this all setup in our repo and either @mraoul or myself will create the docker registry account when we accept it.

**Comment by blacktop** [comment]
Ok I will create a PR.  Thanks guys.
