### ISSUE TITLE
no malware_detector module

### ISSUE THREAD

**Issue by Gunkkk** [MITRECND/chopshop#65]
As it is in docs 

> chopshop - command line interface to ChopShop
> example 7
> ChopShop also supports tees and reverse tees using parens and commas allowing you to feed the output of a module to multiple modules or vice versa. A simple example follows below. Note that a child module (any module on the right hand side of a pipe) needs to be able to accept the types of data that the parents are creating or a warning will be displayed to the screen.
> 
> chopshop -f malware.pcap “(dns, icmp) | malware_detector”

I have not found any module named malware_detector or  maybe it is customized?
Thanks

**Comment by Mraoul** [comment]
"malware_detector" isn't a real decoder it's just a stand in for whatever modules you have access to, e.g, "gh0st_decode" which comes with ChopShop. Those parts of the docs are meant to outline the syntax that chopshop uses/takes
